-- ════════════════════════════════════════════════════════════════════════════
-- E1 · HARDENING (PROPUESTA — NO EJECUTAR TODAVÍA)
--
-- Este fichero NO es una migración: vive en scripts/, fuera de
-- `supabase/migrations/**`, así que el workflow supabase-migrations NO lo aplica.
-- Se decide y se aplica APARTE, después de cerrar la barrera concreta (A).
--
-- ── QUÉ DEFAULT ACL ESTÁ ABIERTO ───────────────────────────────────────────
-- En el esquema `public` hay DOS entradas de pg_default_acl sobre tablas/vistas
-- que conceden el juego COMPLETO a anon y authenticated, medido el 2026-09-02:
--
--   defaclrole = postgres        → anon, authenticated:
--        DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE
--   defaclrole = supabase_admin  → anon, authenticated:  (idéntico)
--
-- Es la causa raíz de R-55 (INC-041, INC-047, INC-073) y de este P0: TODA tabla
-- o vista nueva en `public` nace con todo concedido a los roles públicos. La
-- barrera A cierra la vista concreta; esto cierra la fábrica de agujeros.
--
-- ── QUÉ COMANDO LO CORREGIRÍA ──────────────────────────────────────────────
-- Quitar de los defaults lo que un objeto público nuevo NUNCA debe conceder a
-- anon/authenticated. Hay que hacerlo para los DOS defaclrole, o el que quede
-- sigue abriendo. Ojo: ALTER DEFAULT PRIVILEGES es sensible al rol que lo
-- ejecuta y al FOR ROLE; debe correrse como el rol dueño del default o con FOR
-- ROLE explícito, y verificarse contra pg_default_acl después.
--
--   alter default privileges for role postgres in schema public
--     revoke insert, update, delete, truncate, references, trigger, maintain
--     on tables from anon, authenticated;
--
--   alter default privileges for role supabase_admin in schema public
--     revoke insert, update, delete, truncate, references, trigger, maintain
--     on tables from anon, authenticated;
--
-- (Deja SELECT en el default, que es lo que muchas tablas públicas sí quieren;
--  si se prefiere el criterio inverso —default sin nada y conceder explícito
--  por objeto— es una decisión aparte, más estricta y más ruidosa.)
--
-- ── QUÉ OBJETOS EXISTENTES *NO* MODIFICA ───────────────────────────────────
-- ALTER DEFAULT PRIVILEGES solo afecta a objetos CREADOS DESPUÉS. No cambia ni
-- un solo privilegio de ninguna tabla o vista que YA exista: ni usuarios, ni
-- usuarios_publicos, ni cv_express, ni nada. Por eso NO sustituye a la barrera A
-- —esa arregla el objeto ya existente— y por eso es seguro en el sentido de que
-- no puede romper un consumidor actual: nada de lo desplegado cambia.
--
-- ── ROLLBACK ───────────────────────────────────────────────────────────────
-- Simétrico: volver a conceder en el default lo revocado.
--
--   alter default privileges for role postgres in schema public
--     grant insert, update, delete, truncate, references, trigger, maintain
--     on tables to anon, authenticated;
--   alter default privileges for role supabase_admin in schema public
--     grant insert, update, delete, truncate, references, trigger, maintain
--     on tables to anon, authenticated;
--
-- Y como no tocó ningún objeto existente, revertir el default tampoco los toca:
-- el rollback es completo y sin residuo.
--
-- ── VERIFICACIÓN (solo lectura, tras aplicar) ──────────────────────────────
--   select d.defaclrole::regrole::text, a.grantee::regrole::text,
--          string_agg(a.privilege_type, ', ' order by a.privilege_type)
--   from pg_default_acl d, lateral aclexplode(d.defaclacl) a
--   where d.defaclnamespace='public'::regnamespace
--     and a.grantee::regrole::text in ('anon','authenticated')
--   group by 1,2;
--   -- esperado tras E1: para tablas, solo SELECT (o nada) en ambos defaclrole.
-- ════════════════════════════════════════════════════════════════════════════
